sonar.projectKey=maulidaanuraffh_Proyek3-PPLBW
sonar.organization=maulidaanuraffh
sonar.projectName=Modul 3 - 251511017 Maulida Nur Afifah
sonar.sources=app,routes,resources
sonar.exclusions=**/vendor/**,**/storage/**,**/bootstrap/cache/**,**/public/build/**
sonar.sourceEncoding=UTF-8